# ===================================================================
# CONFIGURACIÓN DEL MICROSERVICIO: REGION (ms-region)
# ===================================================================
spring.application.name=ms-region
server.port=8081

# 1. Conexión a la Base de Datos en XAMPP
# (Crea una base de datos en phpMyAdmin llamada 'db_restaurante' para que todo se guarde ahí de forma centralizada)
spring.datasource.url=jdbc:mysql://localhost:3306/db_restaurante?serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Configuración de Hibernate (JPA)
# 'update' es OBLIGATORIO para que cree de forma automática la tabla 'region' en XAMPP
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 3. Desactivar Eureka por ahora (Evita errores de conexión en consola)
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# 4. Desactivar Flyway para que Hibernate controle las tablas sin interferencias
spring.flyway.enabled=false

spring.sql.init.mode=always

# Le dice a Hibernate que no borre los datos después de insertarlos
spring.jpa.defer-datasource-initialization=true